cd "/Users/jinyuanliu/Desktop/Projects/ongoing/heritage/data"
use county_csmar.dta, clear
gen treat = 0
gen post = 0
gen policyyear = .


// 2014年第一批
replace treat = 1 if county == "丰台区"
replace treat = 1 if county == "延庆县"
replace treat = 1 if county == "北辰区"
replace treat = 1 if county == "蓟县"
replace treat = 1 if county == "桥西区" & prefecture == "石家庄市"
replace treat = 1 if county == "张北县"
replace treat = 1 if county == "丰润区"
replace treat = 1 if county == "清苑县"
replace treat = 1 if county == "易县"
replace treat = 1 if county == "邯山区"
replace treat = 1 if county == "灵丘县"
replace treat = 1 if prefecture == "阳泉市" & county == "郊区"
replace treat = 1 if county == "武乡县"
replace treat = 1 if county == "忻府区"
replace treat = 1 if county == "左权县"
replace treat = 1 if county == "武川县"
replace treat = 1 if county == "海拉尔区"
replace treat = 1 if county == "新巴尔虎左旗"
replace treat = 1 if county == "大东区"
replace treat = 1 if county == "皇姑区"
replace treat = 1 if county == "太平区"
replace treat = 1 if county == "新抚区"
replace treat = 1 if county == "本溪满族自治县"
replace treat = 1 if county == "宽城区"
replace treat = 1 if county == "浑江区"
replace treat = 1 if county == "南岗区"
replace treat = 1 if county == "平房区"
replace treat = 1 if county == "孙吴县"
replace treat = 1 if county == "东宁县"
replace treat = 1 if county == "林口县"
replace treat = 1 if county == "虹口区"
replace treat = 1 if county == "宝山区"
replace treat = 1 if county == "建邺区"
replace treat = 1 if county == "玄武区"
replace treat = 1 if county == "鼓楼区"
replace treat = 1 if county == "赣榆县"
replace treat = 1 if county == "淮阴区"
replace treat = 1 if county == "亭湖区"
replace treat = 1 if county == "上城区"
replace treat = 1 if county == "柯城区"
replace treat = 1 if county == "婺城区"
replace treat = 1 if county == "大通区"
replace treat = 1 if county == "泾县"
replace treat = 1 if county == "庐山区"
replace treat = 1 if county == "上高县"
replace treat = 1 if county == "栖霞市"
replace treat = 1 if county == "海阳市"
replace treat = 1 if county == "乳山市"
replace treat = 1 if county == "兰山区"
replace treat = 1 if county == "费县"
replace treat = 1 if county == "台儿庄区"
replace treat = 1 if county == "薛城区"
replace treat = 1 if county == "滕州市"
replace treat = 1 if county == "镇平县"
replace treat = 1 if county == "扶沟县"
replace treat = 1 if county == "江夏区"
replace treat = 1 if county == "宜城市"
replace treat = 1 if county == "武陵区"
replace treat = 1 if county == "南县"
replace treat = 1 if county == "雁峰区"
replace treat = 1 if county == "南岳区"
replace treat = 1 if county == "芷江侗族自治县"
replace treat = 1 if county == "天河区"
replace treat = 1 if county == "博罗县"
replace treat = 1 if county == "兴宁市"
replace treat = 1 if county == "琼山区"
replace treat = 1 if county == "渝中区"
replace treat = 1 if county == "万州区"
replace treat = 1 if county == "翠屏区"
replace treat = 1 if county == "晴隆县"
replace treat = 1 if county == "腾冲县"
replace treat = 1 if county == "龙陵县"
replace treat = 1 if county == "碑林区"
replace treat = 1 if county == "宝塔区"
replace treat = 1 if county == "子长县"
replace treat = 1 if county == "洛川县"

replace policyyear = 2014 if treat == 1

//2015年第二批

// "亭湖区" "淮阴区" "赣榆县" 玄武区 "建邺区" "南岗区"

replace treat = 1 if county == "丰台区"
replace treat = 1 if county == "海淀区"
replace treat = 1 if county == "房山区"
replace treat = 1 if county == "顺义区"
replace treat = 1 if county == "密云县"
replace treat = 1 if county == "藁城区"
replace treat = 1 if county == "路南区"
replace treat = 1 if county == "滦南县"
replace treat = 1 if county == "迁西县"
replace treat = 1 if county == "涉县"
replace treat = 1 if county == "阜平县"
replace treat = 1 if county == "唐县"
replace treat = 1 if county == "涞源县"
replace treat = 1 if county == "双桥区"
replace treat = 1 if county == "献县"
replace treat = 1 if county == "云冈区"
replace treat = 1 if county == "灵丘县"
replace treat = 1 if county == "城区" & prefecture == "长治市"
replace treat = 1 if county == "黎城县"
replace treat = 1 if county == "武乡县"
replace treat = 1 if county == "平鲁区"
replace treat = 1 if county == "左权县"
replace treat = 1 if county == "兴县"
replace treat = 1 if county == "土默特左旗"
replace treat = 1 if county == "达尔罕茂明安联合旗"
replace treat = 1 if county == "阿荣旗"
replace treat = 1 if county == "鄂温克族自治旗"
replace treat = 1 if county == "五原县"
replace treat = 1 if county == "阿尔山市"
replace treat = 1 if county == "和平区"
replace treat = 1 if county == "大东区"
replace treat = 1 if county == "新抚区"
replace treat = 1 if county == "双塔区"
replace treat = 1 if county == "船营区"
replace treat = 1 if county == "舒兰市"
replace treat = 1 if county == "延吉市"
replace treat = 1 if county == "香坊区"
replace treat = 1 if county == "泰来县"
replace treat = 1 if county == "虎林市"
replace treat = 1 if county == "饶河县"
replace treat = 1 if county == "闸北区"
replace treat = 1 if county == "杨浦区"
replace treat = 1 if county == "金山区"
replace treat = 1 if county == "邳州市"
replace treat = 1 if county == "溧阳市"
replace treat = 1 if county == "常熟市"
replace treat = 1 if county == "海安县"
replace treat = 1 if county == "高邮市"
replace treat = 1 if county == "海陵区"
replace treat = 1 if county == "泗洪县"
replace treat = 1 if county == "富阳市"
replace treat = 1 if county == "鄞州区"
replace treat = 1 if county == "庐江县"
replace treat = 1 if county == "镜湖区"
replace treat = 1 if county == "定远县"
replace treat = 1 if county == "埇桥区"
replace treat = 1 if county == "永安市"
replace treat = 1 if county == "西湖区"
replace treat = 1 if county == "德安县"
replace treat = 1 if county == "彭泽县"
replace treat = 1 if county == "周村区"
replace treat = 1 if county == "山亭区"
replace treat = 1 if county == "梁山县"
replace treat = 1 if county == "岱岳区"
replace treat = 1 if county == "肥城市"
replace treat = 1 if county == "文登区"
replace treat = 1 if county == "沂水县"
replace treat = 1 if county == "莒南县"
replace treat = 1 if county == "临沭县"
replace treat = 1 if county == "乐陵市"
replace treat = 1 if county == "莘县"
replace treat = 1 if county == "曹县"
replace treat = 1 if county == "清丰县"
replace treat = 1 if county == "江岸区"
replace treat = 1 if county == "夷陵区"
replace treat = 1 if county == "大悟县"
replace treat = 1 if county == "岳麓区"
replace treat = 1 if county == "岳阳县"
replace treat = 1 if county == "溆浦县"
replace treat = 1 if county == "金湾区"
replace treat = 1 if county == "顺德区"
replace treat = 1 if county == "东莞市"
replace treat = 1 if county == "叠彩区"
replace treat = 1 if county == "万宁市"
replace treat = 1 if county == "渝中区"
replace treat = 1 if county == "镇远县"
replace treat = 1 if county == "五华区"
replace treat = 1 if county == "龙陵县"
replace treat = 1 if county == "瑞丽市"
replace treat = 1 if county == "泸水县"
replace treat = 1 if county == "新城区"
replace treat = 1 if county == "宝塔区"
replace treat = 1 if county == "天山区"

replace policyyear = 2015 if treat == 1 & policyyear == .


replace treat = 1 if county == "门头沟区"
replace treat = 1 if county == "密云区"
replace treat = 1 if county == "和平区"
replace treat = 1 if county == "灵寿县"
replace treat = 1 if county == "遵化市"
replace treat = 1 if county == "峰峰矿区"
replace treat = 1 if county == "信都区"
replace treat = 1 if county == "南宫市"
replace treat = 1 if county == "安新县"
replace treat = 1 if county == "河间市"
replace treat = 1 if county == "杏花岭区"
replace treat = 1 if county == "潞城区"
replace treat = 1 if county == "阳城县"
replace treat = 1 if county == "辽阳镇"
replace treat = 1 if county == "五台县"
replace treat = 1 if county == "代县"
replace treat = 1 if county == "新城区" & prefecture == "呼和浩特市"
replace treat = 1 if county == "玉泉区"
replace treat = 1 if county == "乌拉特中旗"
replace treat = 1 if county == "桓仁满族自治县"
replace treat = 1 if county == "大石桥市"
replace treat = 1 if county == "双台子区"
replace treat = 1 if county == "丰满区"
replace treat = 1 if county == "西安区"
replace treat = 1 if county == "靖宇县"
replace treat = 1 if county == "敦化市"
replace treat = 1 if county == "尚志市"
replace treat = 1 if county == "汤原县"
replace treat = 1 if county == "宝山区"
replace treat = 1 if county == "秦淮区"
replace treat = 1 if county == "江宁区"
replace treat = 1 if county == "淮安区"
replace treat = 1 if county == "阜宁县"
replace treat = 1 if county == "句容市"
replace treat = 1 if county == "余姚市"
replace treat = 1 if county == "长兴县"
replace treat = 1 if county == "潜山市"
replace treat = 1 if county == "岳西县"
replace treat = 1 if county == "徽州区"
replace treat = 1 if county == "舒城县"
replace treat = 1 if county == "大田县"
replace treat = 1 if county == "高安市"
replace treat = 1 if county == "莱芜区"
replace treat = 1 if county == "张店区"
replace treat = 1 if county == "淄川区"
replace treat = 1 if county == "莱州市"
replace treat = 1 if county == "寿光市"
replace treat = 1 if county == "岱岳区"
replace treat = 1 if county == "肥城市"
replace treat = 1 if county == "文登区"
replace treat = 1 if county == "沂水县"
replace treat = 1 if county == "莒南县"
replace treat = 1 if county == "临沭县"
replace treat = 1 if county == "乐陵市"
replace treat = 1 if county == "莘县"
replace treat = 1 if county == "曹县"
replace treat = 1 if county == "济源市"
replace treat = 1 if county == "夷陵区"
replace treat = 1 if county == "鄂城区"
replace treat = 1 if county == "安陆市"
replace treat = 1 if county == "大悟县"
replace treat = 1 if county == "岳麓区"
replace treat = 1 if county == "龙华区"
replace treat = 1 if county == "中山市"
replace treat = 1 if county == "七星区"
replace treat = 1 if county == "渝中区"
replace treat = 1 if county == "北碚区"
replace treat = 1 if county == "青羊区"
replace treat = 1 if county == "独山县"
replace treat = 1 if county == "施甸县"
replace treat = 1 if county == "龙陵县"
replace treat = 1 if county == "芒市"
replace treat = 1 if county == "泾阳县"
replace treat = 1 if county == "宝塔区"
replace treat = 1 if county == "城固县"
replace treat = 1 if county == "城关区"


* 设置对应年份
replace policyyear = 2020 if treat == 1 & policyyear == .

replace post = 1 if year >= policyyear
save county_did.dta, replace



merge m:n countyid year using cultural_firm.dta
drop _merge
winsor2 firm, cut(1,99) replace
gen lnfirm = ln(firm + 1)

gen did = 0

replace did = treat * post

reghdfe lnfirm did, a(countyid year) vce(cluster countyid)
